"""
app/services/ai/recommendation.py
---------------------------------
Parses and stores actionable recommendations generated by the AI Service.
"""

from typing import List, Dict
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.logging import get_logger
from app.core.constants import RecommendationPriority, RecommendationStatus
from app.models.recommendation import Recommendation


logger = get_logger(__name__)


class RecommendationEngine:
    def __init__(self, db: AsyncSession):
        self._db = db

    async def process_recommendations(self, insight_id: UUID, recommendations_data: List[Dict]):
        """
        Takes raw recommendation dictionaries from Gemini and creates database rows.
        """
        valid_priorities = [RecommendationPriority.LOW, RecommendationPriority.MEDIUM, RecommendationPriority.HIGH]
        
        for item in recommendations_data:
            text = item.get("recommendation")
            priority = item.get("priority", "medium").lower()
            
            if not text:
                continue
                
            if priority not in valid_priorities:
                priority = RecommendationPriority.MEDIUM
                
            rec = Recommendation(
                insight_id=insight_id,
                recommendation=text,
                priority=priority,
                status=RecommendationStatus.PENDING,
            )
            self._db.add(rec)
            
        await self._db.flush()
        logger.info("Saved recommendations", extra={"insight_id": str(insight_id), "count": len(recommendations_data)})
