"""
app/models/user.py
------------------
SQLAlchemy 2 model for the ``users`` table.

Schema (from Database Design Document):
    id          UUID PK  gen_random_uuid()
    email       TEXT     UNIQUE NOT NULL
    full_name   TEXT
    avatar_url  TEXT
    role        TEXT     (UserRole enum: admin | member | viewer)
    created_at  TIMESTAMPTZ  NOT NULL  default now()
    updated_at  TIMESTAMPTZ  NOT NULL  default now()

Relationships (defined here, back-populated in child models):
    projects        → Project.owner_id
    project_members → ProjectMember.user_id
    activity_logs   → ActivityLog.user_id
"""

import uuid
from typing import TYPE_CHECKING, List

from sqlalchemy import String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.constants import UUID_GEN, UserRole
from app.database.base import Base
from app.models.mixins import TimestampMixin

if TYPE_CHECKING:
    from app.models.project import Project
    from app.models.project_member import ProjectMember
    from app.models.activity_log import ActivityLog


class User(TimestampMixin, Base):
    """Represents a platform user (synced from Supabase Auth)."""

    __tablename__ = "users"

    # ------------------------------------------------------------------ #
    # Primary key
    # ------------------------------------------------------------------ #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        doc="Unique user identifier (UUID v4, generated by PostgreSQL).",
    )

    # ------------------------------------------------------------------ #
    # Columns
    # ------------------------------------------------------------------ #
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        doc="User's email address. Must be unique across all users.",
    )
    full_name: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        doc="User's display name.",
    )
    avatar_url: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="URL to the user's profile picture (Supabase Storage or external CDN).",
    )
    role: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default=UserRole.MEMBER,
        server_default=UserRole.MEMBER,
        doc="Platform-level role: admin | member | viewer.",
    )

    # ------------------------------------------------------------------ #
    # Relationships
    # ------------------------------------------------------------------ #
    projects: Mapped[List["Project"]] = relationship(
        "Project",
        back_populates="owner",
        cascade="all, delete-orphan",
        lazy="select",
        doc="Projects owned by this user.",
    )
    project_memberships: Mapped[List["ProjectMember"]] = relationship(
        "ProjectMember",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="select",
        doc="Projects this user is a member of (via project_members join table).",
    )
    activity_logs: Mapped[List["ActivityLog"]] = relationship(
        "ActivityLog",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="select",
        doc="Audit trail of actions performed by this user.",
    )

    def __repr__(self) -> str:
        return f"<User id={self.id} email={self.email!r}>"
